public enum NOTIFY {
    REGISTER,

    UPDATE_BOOK,
    UPDATE_CATEGORY,
    UPDATE_AUTHOR,
    UPDATE_NOTIFICATION,
    UPDATE_BOOK_COPY,
    UPDATE_PUBLISHED,
    UPDATE_CHECKOUT,
    UPDATE_HOLD,

    CLIENT_UPDATE_NOTIFICATION,
    CLIENT_UPDATE_CHECKOUT,
}
